version: "3"
services:
    postgres-db:
        image: postgres
        container_name: postgres-db
        restart: always
        ports:
            - "1234:5432"
        env_file:
            - ./apps/api/.env
        volumes:
            - volume_db:/var/lib/postgresql/data

    verzel-project-api:
        container_name: verzel-project-api
        build: ./apps/api
        ports:
            - 5000:5000
        depends_on:
            - postgres-db
        env_file:
            - ./apps/api/.env

    verzel-project-client:
        container_name: verzel-project-client
        build: ./apps/client
        volumes:
            - build_react:/var/www/html

    nginx:
        container_name: nginx
        build: ./nginx
        ports:
            - 8080:80
        volumes:
            - build_react:/var/www/html
        depends_on:
            - postgres-db
            - verzel-project-api
            - verzel-project-client

volumes:
    volume_db:
    build_react:
